service: zillow-scrape
frameworkVersion: '2.15.0'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

custom:
  pythonRequirements:
    pythonBin: python3
    requests: true
    unicodecsv: true
    lxml: true
    fileName: requirements.txt
    dockerizePip: true
    noDeploy:
      - boto3
      - botocore
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - s3transfer
      # - setuptools
      - six

package:
  individually: false
  excludeDevDependencies: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
    timeout: 30
  scrape:
    handler: handler.scrape
    events:
      - http:
          path: scrape
          method: get
    timeout: 900

plugins:
  - serverless-python-requirements
