service: zillow-scrape
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1

custom:
  pythonRequirements:
    requests: true
    lxml: true
    unicodecsv: true
    boto3: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-python-requirements
