service: zillow-scrape
frameworkVersion: '1.83.2'

provider:
  name: aws
  runtime: python3.7
  region: us-east-1

custom:
  pythonRequirements:
    pythonBin: python3
    requests: true
    lxml: true
    unicodecsv: true
    python3-setuptools: true

package:
  individually: false
  excludeDevDependencies: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-python-requirements
